### ISSUE TITLE
What is partition `env` for, do we store something on it?

### ISSUE THREAD

**Issue by amazingfate** [jaredmcneill/quartz64_uefi#59]
I want to create a 16MB or 8MB image for spi flash. But the 16MB env partition is stopping me. Is this partition necessary?

**Comment by S199pWa1k9r** [comment]
I really want to add an UNDI driver for RTL8125GB and a UEFI image, 
but this is not possible because the maximum binary code size will be exceeded.
At the same time, 
the UEFI image for RK356X is much larger than for RK3588 because it contains RockChip blobs. Can we stop using them?
This will solve problems with the overall UEFI size.
